# .github/workflows/ci.yml

name: Swift CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Збірка та тестування на macOS
    runs-on: macos-latest

    steps:
      - name: Отримання коду
        uses: actions/checkout@v4

      - name: Збірка та тестування за допомогою Xcode
        run: |
          xcodebuild clean build test \
            -project "TestNewProject.xcodeproj" \
            -scheme "TestNewProject" \
            -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=17.5"
