name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Show available simulators
        run: xcrun simctl list devices

      - name: Build project
        run: |
          xcodebuild \
            -project "TestNewProject.xcodeproj" \
            -scheme "TestNewProject" \
            -sdk iphonesimulator \
            -configuration Debug \
            clean build

      - name: Run tests
        run: |
          xcodebuild test \
            -project "TestNewProject.xcodeproj" \
            -scheme "TestNewProject" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6'
