name: iOS CI          # Назва сценарію (можеш назвати як хочеш)

on:                   # Коли запускати
  push:               # при пуші коду
    branches: [ main, develop ]   # тільки для цих гілок
  pull_request:       # і при створенні PR

jobs:                 # що треба зробити
  build-and-test:     # ім'я джоби
    runs-on: macos-latest   # кажемо GitHub: дай мені віртуальний Mac

    steps:            # кроки (послідовність команд)
      - name: Checkout code   # 1. забрати код із репо
        uses: actions/checkout@v4

      - name: Show Xcode version   # 2. просто показати, яка Xcode стоїть на машині
        run: xcodebuild -version

      - name: Build project   # 3. зібрати додаток
        run: |
          xcodebuild \
            -project "TestNewProject.xcodeproj" \   # тут підстав свій файл
            -scheme "ios" \              # тут назву своєї схеми
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build

      - name: Run tests   # 4. прогнати тести
        run: |
          xcodebuild test \
            -project "TestNewProject.xcodeproj" \
            -scheme "ios" \
            -destination 'platform=iOS Simulator,name=iPhone 15'
