name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # 1️⃣ Забираємо код із репо
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Показуємо версію Xcode
      - name: Show Xcode version
        run: xcodebuild -version

      # 3️⃣ Збираємо проект (без UI тестів)
      - name: Build project
        run: |
          xcodebuild \
            -project "TestNewProject.xcodeproj" \
            -scheme "TestNewProject" \
            -sdk iphonesimulator \
            -configuration Debug \
            clean build

      # 4️⃣ Проганяємо тільки unit-тести
      - name: Run unit tests
        run: |
          xcodebuild test \
            -project "TestNewProject.xcodeproj" \
            -scheme "TestNewProject" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6' \
            -only-testing:TestNewProjectTests
