name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # 1️⃣ Забрати код із репо
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Показати версію Xcode
      - name: Show Xcode version
        run: xcodebuild -version

      # 3️⃣ Збірка проекту
      - name: Build project
        run: |
          xcodebuild \
            -project "TestNewProject.xcodeproj" \
            -scheme "TestNewProject" \
            -configuration Debug \
            clean build

      # 4️⃣ Проганяємо unit-тести (без симулятора)
      - name: Run unit tests
        run: |
          xcodebuild test \
            -project "TestNewProject.xcodeproj" \
            -scheme "TestNewProject" \
            -configuration Debug \
            -enableCodeCoverage YES
